import type { ComponentType } from "react";
import {
  RiDashboardLine,
  RiMailLine,
  RiBuildingLine,
  RiAddLine,
  RiEditLine,
  RiDeleteBinLine,
  RiImageLine,
  RiEyeLine,
  RiStarLine,
  RiCloseLine,
  RiSearchLine,
  RiPhoneLine,
  RiCalendarLine,
  RiTimeLine,
  RiUserLine,
  RiFilterLine,
  RiSortAsc,
  RiDownloadLine,
  RiUploadLine,
  RiShareLine,
  RiLinksLine,
  RiExternalLinkLine,
  RiSubtractLine,
  RiErrorWarningLine,
  RiInformationLine,
  RiQuestionLine,
  RiFireLine,
  RiLeafLine,
  RiCloudLine,
  RiRainyLine,
  RiSnowyLine,
  RiWindyLine,
  RiFoggyLine,
  RiHazeLine,
  RiDrizzleLine,
  RiShowersLine,
  RiFileTextLine,
  RiArticleLine,
  RiBookLine,
  RiBriefcaseLine,
  RiCalendarCheckLine,
  RiChat1Line,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiCustomerServiceLine,
  RiDatabaseLine,
  RiDeviceLine,
  RiDiscussLine,
  RiFlagLine,
  RiFlashlightLine,
  RiFoldersLine,
  RiGalleryLine,
  RiGlobalLine,
  RiGovernmentLine,
  RiHandHeartLine,
  RiHealthBookLine,
  RiHeartLine,
  RiHomeLine,
  RiHospitalLine,
  RiInfinityLine,
  RiInputMethodLine,
  RiLightbulbLine,
  RiMapPinLine,
  RiMapPinUserLine,
  RiPulseLine,
  RiRestaurantLine,
  RiRocketLine,
  RiSafeLine,
  RiServerLine,
  RiServiceLine,
  RiSettings3Line,
  RiShieldLine,
  RiShoppingBagLine,
  RiShoppingCartLine,
  RiSuitcaseLine,
  RiTimerLine,
  RiTrophyLine,
  RiTruckLine,
  RiUser2Line,
  RiUser3Line,
  RiUserAddLine,
  RiUserCommunityLine,
  RiUserFollowLine,
  RiUserHeartLine,
  RiUserLocationLine,
  RiUserReceivedLine,
  RiUserSearchLine,
  RiUserSettingsLine,
  RiUserSharedLine,
  RiUserSmileLine,
  RiVideoLine,
  RiVipCrownLine,
  RiWalletLine,
} from "react-icons/ri";

export interface IconDef {
  name: string;
  category: string;
}

export const iconComponents: Record<string, ComponentType<{ size?: number; className?: string }>> = {
  RiFileTextLine,
  RiArticleLine,
  RiBookLine,
  RiImageLine,
  RiGalleryLine,
  RiVideoLine,
  RiGlobalLine,
  RiUserSettingsLine,
  RiStarLine,
  RiTrophyLine,
  RiVipCrownLine,
  RiHeartLine,
  RiPulseLine,
  RiHealthBookLine,
  RiHandHeartLine,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiBriefcaseLine,
  RiSuitcaseLine,
  RiBuildingLine,
  RiHospitalLine,
  RiHomeLine,
  RiEyeLine,
  RiChat1Line,
  RiDiscussLine,
  RiCustomerServiceLine,
  RiMailLine,
  RiPhoneLine,
  RiMapPinLine,
  RiMapPinUserLine,
  RiCalendarLine,
  RiCalendarCheckLine,
  RiTimerLine,
  RiTimeLine,
  RiSettings3Line,
  RiDashboardLine,
  RiUserLine,
  RiUser2Line,
  RiUser3Line,
  RiUserAddLine,
  RiUserFollowLine,
  RiUserHeartLine,
  RiUserLocationLine,
  RiUserSearchLine,
  RiUserSmileLine,
  RiUserCommunityLine,
  RiSearchLine,
  RiFilterLine,
  RiSortAsc,
  RiDownloadLine,
  RiUploadLine,
  RiShareLine,
  RiLinksLine,
  RiExternalLinkLine,
  RiAddLine,
  RiSubtractLine,
  RiCloseLine,
  RiErrorWarningLine,
  RiInformationLine,
  RiQuestionLine,
  RiLightbulbLine,
  RiFlashlightLine,
  RiFireLine,
  RiRocketLine,
  RiLeafLine,
  RiCloudLine,
  RiRainyLine,
  RiSnowyLine,
  RiWindyLine,
  RiFoggyLine,
  RiHazeLine,
  RiDrizzleLine,
  RiShowersLine,
  RiDatabaseLine,
  RiServerLine,
  RiDeviceLine,
  RiFlagLine,
  RiFoldersLine,
  RiGovernmentLine,
  RiInfinityLine,
  RiInputMethodLine,
  RiRestaurantLine,
  RiSafeLine,
  RiServiceLine,
  RiShieldLine,
  RiShoppingBagLine,
  RiShoppingCartLine,
  RiTruckLine,
  RiUserReceivedLine,
  RiUserSharedLine,
  RiWalletLine,
};

export const availableIcons: IconDef[] = [
  { name: "RiFileTextLine", category: "Document" },
  { name: "RiArticleLine", category: "Document" },
  { name: "RiBookLine", category: "Education" },
  { name: "RiImageLine", category: "Media" },
  { name: "RiGalleryLine", category: "Media" },
  { name: "RiVideoLine", category: "Media" },
  { name: "RiGlobalLine", category: "World" },
  { name: "RiUserSettingsLine", category: "User" },
  { name: "RiStarLine", category: "Star" },
  { name: "RiTrophyLine", category: "Award" },
  { name: "RiVipCrownLine", category: "VIP" },
  { name: "RiHeartLine", category: "Health" },
  { name: "RiPulseLine", category: "Health" },
  { name: "RiHealthBookLine", category: "Health" },
  { name: "RiHandHeartLine", category: "Health" },
  { name: "RiCheckLine", category: "Check" },
  { name: "RiCheckboxCircleLine", category: "Check" },
  { name: "RiBriefcaseLine", category: "Business" },
  { name: "RiSuitcaseLine", category: "Business" },
  { name: "RiBuildingLine", category: "Building" },
  { name: "RiHospitalLine", category: "Hospital" },
  { name: "RiHomeLine", category: "Home" },
  { name: "RiEyeLine", category: "Vision" },
  { name: "RiChat1Line", category: "Chat" },
  { name: "RiDiscussLine", category: "Chat" },
  { name: "RiCustomerServiceLine", category: "Support" },
  { name: "RiMailLine", category: "Email" },
  { name: "RiPhoneLine", category: "Phone" },
  { name: "RiMapPinLine", category: "Location" },
  { name: "RiMapPinUserLine", category: "Location" },
  { name: "RiCalendarLine", category: "Calendar" },
  { name: "RiCalendarCheckLine", category: "Calendar" },
  { name: "RiTimerLine", category: "Time" },
  { name: "RiTimeLine", category: "Time" },
  { name: "RiSettings3Line", category: "Settings" },
  { name: "RiDashboardLine", category: "Dashboard" },
  { name: "RiUserLine", category: "User" },
  { name: "RiUser2Line", category: "User" },
  { name: "RiUser3Line", category: "User" },
  { name: "RiUserAddLine", category: "User" },
  { name: "RiUserFollowLine", category: "User" },
  { name: "RiUserHeartLine", category: "User" },
  { name: "RiUserLocationLine", category: "User" },
  { name: "RiUserSearchLine", category: "User" },
  { name: "RiUserSmileLine", category: "User" },
  { name: "RiUserCommunityLine", category: "Group" },
  { name: "RiSearchLine", category: "Search" },
  { name: "RiFilterLine", category: "Filter" },
  { name: "RiSortAsc", category: "Sort" },
  { name: "RiDownloadLine", category: "Download" },
  { name: "RiUploadLine", category: "Upload" },
  { name: "RiShareLine", category: "Share" },
  { name: "RiLinksLine", category: "Link" },
  { name: "RiExternalLinkLine", category: "External" },
  { name: "RiAddLine", category: "Add" },
  { name: "RiSubtractLine", category: "Minus" },
  { name: "RiCloseLine", category: "Close" },
  { name: "RiErrorWarningLine", category: "Warning" },
  { name: "RiInformationLine", category: "Info" },
  { name: "RiQuestionLine", category: "Question" },
  { name: "RiLightbulbLine", category: "Idea" },
  { name: "RiFlashlightLine", category: "Flash" },
  { name: "RiFireLine", category: "Fire" },
  { name: "RiRocketLine", category: "Rocket" },
  { name: "RiLeafLine", category: "Nature" },
  { name: "RiCloudLine", category: "Cloud" },
  { name: "RiRainyLine", category: "Rain" },
  { name: "RiSnowyLine", category: "Snow" },
  { name: "RiWindyLine", category: "Wind" },
  { name: "RiFoggyLine", category: "Fog" },
  { name: "RiHazeLine", category: "Haze" },
  { name: "RiDrizzleLine", category: "Rain" },
  { name: "RiShowersLine", category: "Rain" },
  { name: "RiDatabaseLine", category: "Database" },
  { name: "RiServerLine", category: "Server" },
  { name: "RiDeviceLine", category: "Device" },
  { name: "RiFlagLine", category: "Flag" },
  { name: "RiFoldersLine", category: "Folders" },
  { name: "RiGovernmentLine", category: "Government" },
  { name: "RiInfinityLine", category: "Infinity" },
  { name: "RiInputMethodLine", category: "Input" },
  { name: "RiRestaurantLine", category: "Restaurant" },
  { name: "RiSafeLine", category: "Safe" },
  { name: "RiServiceLine", category: "Service" },
  { name: "RiShieldLine", category: "Shield" },
  { name: "RiShoppingBagLine", category: "Shopping" },
  { name: "RiShoppingCartLine", category: "Shopping" },
  { name: "RiTruckLine", category: "Truck" },
  { name: "RiUserReceivedLine", category: "User" },
  { name: "RiUserSharedLine", category: "User" },
  { name: "RiWalletLine", category: "Wallet" },
];
