import type { ComponentType } from "react";
import {
  RiDashboardLine,
  RiMailLine,
  RiBuildingLine,
  RiAddLine,
  RiEditLine,
  RiDeleteBinLine,
  RiImageLine,
  RiEyeLine,
  RiStarLine,
  RiCloseLine,
  RiSearchLine,
  RiPhoneLine,
  RiCalendarLine,
  RiTimeLine,
  RiUserLine,
  RiFilterLine,
  RiSortAsc,
  RiDownloadLine,
  RiUploadLine,
  RiShareLine,
  RiLinksLine,
  RiExternalLinkLine,
  RiSubtractLine,
  RiErrorWarningLine,
  RiInformationLine,
  RiQuestionLine,
  RiFireLine,
  RiLeafLine,
  RiCloudLine,
  RiRainyLine,
  RiSnowyLine,
  RiWindyLine,
  RiFoggyLine,
  RiHazeLine,
  RiDrizzleLine,
  RiShowersLine,
  RiFileTextLine,
  RiArticleLine,
  RiBookLine,
  RiBriefcaseLine,
  RiCalendarCheckLine,
  RiChat1Line,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiCustomerServiceLine,
  RiDatabaseLine,
  RiDeviceLine,
  RiDiscussLine,
  RiFlagLine,
  RiFlashlightLine,
  RiFoldersLine,
  RiGalleryLine,
  RiGlobalLine,
  RiGovernmentLine,
  RiHandHeartLine,
  RiHealthBookLine,
  RiHeartLine,
  RiHomeLine,
  RiHospitalLine,
  RiInfinityLine,
  RiInputMethodLine,
  RiLightbulbLine,
  RiMapPinLine,
  RiMapPinUserLine,
  RiPulseLine,
  RiRestaurantLine,
  RiRocketLine,
  RiSafeLine,
  RiServerLine,
  RiServiceLine,
  RiSettings3Line,
  RiShieldLine,
  RiShoppingBagLine,
  RiShoppingCartLine,
  RiSuitcaseLine,
  RiTimerLine,
  RiTrophyLine,
  RiTruckLine,
  RiUser2Line,
  RiUser3Line,
  RiUserAddLine,
  RiUserCommunityLine,
  RiUserFollowLine,
  RiUserHeartLine,
  RiUserLocationLine,
  RiUserReceivedLine,
  RiUserSearchLine,
  RiUserSettingsLine,
  RiUserSharedLine,
  RiUserSmileLine,
  RiVideoLine,
  RiVipCrownLine,
  RiWalletLine,
  // أيقونات جديدة
  RiAddCircleLine,
  RiAlertLine,
  RiBarChart2Line,
  RiBatteryChargeLine,
  RiBluetoothLine,
  RiCameraLine,
  RiCastLine,
  RiCelsiusLine,
  RiCodeLine,
  RiCompassDiscoverLine,
  RiContrastLine,
  RiCouponLine,
  RiCupLine,
  RiDiscountPercentLine,
  RiDraftLine,
  RiDropLine,
  RiEarthLine,
  RiEmotionHappyLine,
  RiEmotionSadLine,
  RiFeedbackLine,
  RiFirstAidKitLine,
  RiFocusLine,
  RiFundsLine,
  RiGiftLine,
  RiGitBranchLine,
  RiGitCommitLine,
  RiGitMergeLine,
  RiGithubLine,
  RiGoogleLine,
  RiGraduationCapLine,
  RiGroupLine,
  RiGuideLine,
  RiHardDriveLine,
  RiHeadphoneLine,
  RiHotelLine,
  RiIdCardLine,
  RiInboxLine,
  RiInstagramLine,
  RiKeyLine,
  RiKeyboardBoxLine,
  RiLineChartLine,
  RiLinkedinBoxLine,
  RiLockLine,
  RiLockUnlockLine,
  RiMagicLine,
  RiMailSendLine,
  RiMedicineBottleLine,
  RiMessengerLine,
  RiMoneyDollarBoxLine,
  RiMoonLine,
  RiMouseLine,
  RiMusicLine,
  RiNotificationLine,
  RiParkingLine,
  RiPaypalLine,
  RiPoliceBadgeLine,
  RiPrinterLine,
  RiQrCodeLine,
  RiRadioLine,
  RiRedditLine,
  RiRefreshLine,
  RiRecycleLine,
  RiRegisteredLine,
  RiRepeatLine,
  RiReplyLine,
  RiRoadMapLine,
  RiRobotLine,
  RiRssLine,
  RiSaveLine,
  RiScanLine,
  RiSchoolLine,
  RiScissorsLine,
  RiSendPlaneLine,
  RiSignalTowerLine,
  RiSkypeLine,
  RiSlackLine,
  RiSnapchatLine,
  RiSoundModuleLine,
  RiSpeakerLine,
  RiSpotifyLine,
  RiStackOverflowLine,
  RiStethoscopeLine,
  RiSunLine,
  RiSwitchLine,
  RiTableAltLine,
  RiTabletLine,
  RiTeamLine,
  RiTelegramLine,
  RiTerminalBoxLine,
  RiThermometerLine,
  RiThumbUpLine,
  RiThumbDownLine,
  RiTicketLine,
  RiTiktokLine,
  RiToolsLine,
  RiTornadoLine,
  RiTrafficLightLine,
  RiTrainLine,
  RiTwitchLine,
  RiTwitterLine,
  RiUmbrellaLine,
  RiUninstallLine,
  RiUsbLine,
  RiVirusLine,
  RiVisaLine,
  RiVolumeDownLine,
  RiVolumeMuteLine,
  RiVolumeUpLine,
  RiWalkLine,
  RiWhatsappLine,
  RiWifiLine,
  RiWindowsLine,
  RiYoutubeLine,
  RiZcoolLine,
  RiZoomInLine,
  RiZoomOutLine,
} from "react-icons/ri";

export interface IconDef {
  name: string;
  category: string;
}

export const iconComponents: Record<string, ComponentType<{ size?: number; className?: string }>> = {
  // أيقونات أساسية
  RiFileTextLine,
  RiArticleLine,
  RiBookLine,
  RiImageLine,
  RiGalleryLine,
  RiVideoLine,
  RiGlobalLine,
  RiUserSettingsLine,
  RiStarLine,
  RiTrophyLine,
  RiVipCrownLine,
  RiHeartLine,
  RiPulseLine,
  RiHealthBookLine,
  RiHandHeartLine,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiBriefcaseLine,
  RiSuitcaseLine,
  RiBuildingLine,
  RiHospitalLine,
  RiHomeLine,
  RiEyeLine,
  RiChat1Line,
  RiDiscussLine,
  RiCustomerServiceLine,
  RiMailLine,
  RiPhoneLine,
  RiMapPinLine,
  RiMapPinUserLine,
  RiCalendarLine,
  RiCalendarCheckLine,
  RiTimerLine,
  RiTimeLine,
  RiSettings3Line,
  RiDashboardLine,
  RiUserLine,
  RiUser2Line,
  RiUser3Line,
  RiUserAddLine,
  RiUserFollowLine,
  RiUserHeartLine,
  RiUserLocationLine,
  RiUserSearchLine,
  RiUserSmileLine,
  RiUserCommunityLine,
  RiSearchLine,
  RiFilterLine,
  RiSortAsc,
  RiDownloadLine,
  RiUploadLine,
  RiShareLine,
  RiLinksLine,
  RiExternalLinkLine,
  RiAddLine,
  RiSubtractLine,
  RiCloseLine,
  RiErrorWarningLine,
  RiInformationLine,
  RiQuestionLine,
  RiLightbulbLine,
  RiFlashlightLine,
  RiFireLine,
  RiRocketLine,
  RiLeafLine,
  RiCloudLine,
  RiRainyLine,
  RiSnowyLine,
  RiWindyLine,
  RiFoggyLine,
  RiHazeLine,
  RiDrizzleLine,
  RiShowersLine,
  RiDatabaseLine,
  RiServerLine,
  RiDeviceLine,
  RiFlagLine,
  RiFoldersLine,
  RiGovernmentLine,
  RiInfinityLine,
  RiInputMethodLine,
  RiRestaurantLine,
  RiSafeLine,
  RiServiceLine,
  RiShieldLine,
  RiShoppingBagLine,
  RiShoppingCartLine,
  RiTruckLine,
  RiUserReceivedLine,
  RiUserSharedLine,
  RiWalletLine,
  // أيقونات جديدة
  RiAddCircleLine,
  RiAlertLine,
  RiBarChart2Line,
  RiBatteryChargeLine,
  RiBluetoothLine,
  RiCameraLine,
  RiCastLine,
  RiCelsiusLine,
  RiCodeLine,
  RiCompassDiscoverLine,
  RiContrastLine,
  RiCouponLine,
  RiCupLine,
  RiDiscountPercentLine,
  RiDraftLine,
  RiDropLine,
  RiEarthLine,
  RiEmotionHappyLine,
  RiEmotionSadLine,
  RiFeedbackLine,
  RiFirstAidKitLine,
  RiFocusLine,
  RiFundsLine,
  RiGiftLine,
  RiGitBranchLine,
  RiGitCommitLine,
  RiGitMergeLine,
  RiGithubLine,
  RiGoogleLine,
  RiGraduationCapLine,
  RiGroupLine,
  RiGuideLine,
  RiHardDriveLine,
  RiHeadphoneLine,
  RiHotelLine,
  RiIdCardLine,
  RiInboxLine,
  RiInstagramLine,
  RiKeyLine,
  RiKeyboardBoxLine,
  RiLineChartLine,
  RiLinkedinBoxLine,
  RiLockLine,
  RiLockUnlockLine,
  RiMagicLine,
  RiMailSendLine,
  RiMedicineBottleLine,
  RiMessengerLine,
  RiMoneyDollarBoxLine,
  RiMoonLine,
  RiMouseLine,
  RiMusicLine,
  RiNotificationLine,
  RiParkingLine,
  RiPaypalLine,
  RiPoliceBadgeLine,
  RiPrinterLine,
  RiQrCodeLine,
  RiRadioLine,
  RiRedditLine,
  RiRefreshLine,
  RiRecycleLine,
  RiRegisteredLine,
  RiRepeatLine,
  RiReplyLine,
  RiRoadMapLine,
  RiRobotLine,
  RiRssLine,
  RiSaveLine,
  RiScanLine,
  RiSchoolLine,
  RiScissorsLine,
  RiSendPlaneLine,
  RiSignalTowerLine,
  RiSkypeLine,
  RiSlackLine,
  RiSnapchatLine,
  RiSoundModuleLine,
  RiSpeakerLine,
  RiSpotifyLine,
  RiStackOverflowLine,
  RiStethoscopeLine,
  RiSunLine,
  RiSwitchLine,
  RiTableAltLine,
  RiTabletLine,
  RiTeamLine,
  RiTelegramLine,
  RiTerminalBoxLine,
  RiThermometerLine,
  RiThumbUpLine,
  RiThumbDownLine,
  RiTicketLine,
  RiTiktokLine,
  RiToolsLine,
  RiTornadoLine,
  RiTrafficLightLine,
  RiTrainLine,
  RiTwitchLine,
  RiTwitterLine,
  RiUmbrellaLine,
  RiUninstallLine,
  RiUsbLine,
  RiVirusLine,
  RiVisaLine,
  RiVolumeDownLine,
  RiVolumeMuteLine,
  RiVolumeUpLine,
  RiWalkLine,
  RiWhatsappLine,
  RiWifiLine,
  RiWindowsLine,
  RiYoutubeLine,
  RiZcoolLine,
  RiZoomInLine,
  RiZoomOutLine,
};

export const availableIcons: IconDef[] = [
  // Document
  { name: "RiFileTextLine", category: "Document" },
  { name: "RiArticleLine", category: "Document" },
  { name: "RiDraftLine", category: "Document" },
  
  // Education
  { name: "RiBookLine", category: "Education" },
  { name: "RiGraduationCapLine", category: "Education" },
  { name: "RiSchoolLine", category: "Education" },
  
  // Media
  { name: "RiImageLine", category: "Media" },
  { name: "RiGalleryLine", category: "Media" },
  { name: "RiVideoLine", category: "Media" },
  { name: "RiCameraLine", category: "Media" },
  { name: "RiMusicLine", category: "Media" },
  { name: "RiHeadphoneLine", category: "Media" },
  { name: "RiSpeakerLine", category: "Media" },
  { name: "RiSoundModuleLine", category: "Media" },
  
  // World
  { name: "RiGlobalLine", category: "World" },
  { name: "RiEarthLine", category: "World" },
  { name: "RiCompassDiscoverLine", category: "World" },
  
  // User
  { name: "RiUserLine", category: "User" },
  { name: "RiUser2Line", category: "User" },
  { name: "RiUser3Line", category: "User" },
  { name: "RiUserAddLine", category: "User" },
  { name: "RiUserFollowLine", category: "User" },
  { name: "RiUserHeartLine", category: "User" },
  { name: "RiUserLocationLine", category: "User" },
  { name: "RiUserSearchLine", category: "User" },
  { name: "RiUserSmileLine", category: "User" },
  { name: "RiUserSettingsLine", category: "User" },
  { name: "RiUserReceivedLine", category: "User" },
  { name: "RiUserSharedLine", category: "User" },
  { name: "RiGroupLine", category: "User" },
  { name: "RiTeamLine", category: "User" },
  { name: "RiIdCardLine", category: "User" },
  
  // Group
  { name: "RiUserCommunityLine", category: "Group" },
  
  // Health
  { name: "RiHeartLine", category: "Health" },
  { name: "RiPulseLine", category: "Health" },
  { name: "RiHealthBookLine", category: "Health" },
  { name: "RiHandHeartLine", category: "Health" },
  { name: "RiFirstAidKitLine", category: "Health" },
  { name: "RiMedicineBottleLine", category: "Health" },
  { name: "RiStethoscopeLine", category: "Health" },
  { name: "RiHospitalLine", category: "Health" },
  { name: "RiVirusLine", category: "Health" },
  
  // Business
  { name: "RiBriefcaseLine", category: "Business" },
  { name: "RiSuitcaseLine", category: "Business" },
  { name: "RiBuildingLine", category: "Business" },
  { name: "RiServiceLine", category: "Business" },
  { name: "RiFundsLine", category: "Business" },
  { name: "RiBarChart2Line", category: "Business" },
  { name: "RiLineChartLine", category: "Business" },
  
  // Chat
  { name: "RiChat1Line", category: "Chat" },
  { name: "RiDiscussLine", category: "Chat" },
  { name: "RiMessengerLine", category: "Chat" },
  { name: "RiSendPlaneLine", category: "Chat" },
  { name: "RiFeedbackLine", category: "Chat" },
  
  // Communication
  { name: "RiMailLine", category: "Communication" },
  { name: "RiPhoneLine", category: "Communication" },
  { name: "RiMailSendLine", category: "Communication" },
  { name: "RiInboxLine", category: "Communication" },
  { name: "RiNotificationLine", category: "Communication" },
  
  // Location
  { name: "RiMapPinLine", category: "Location" },
  { name: "RiMapPinUserLine", category: "Location" },
  { name: "RiRoadMapLine", category: "Location" },
  { name: "RiParkingLine", category: "Location" },
  { name: "RiTrafficLightLine", category: "Location" },
  { name: "RiTrainLine", category: "Location" },
  { name: "RiWalkLine", category: "Location" },
  
  // Calendar & Time
  { name: "RiCalendarLine", category: "Calendar" },
  { name: "RiCalendarCheckLine", category: "Calendar" },
  { name: "RiTimerLine", category: "Time" },
  { name: "RiTimeLine", category: "Time" },
  
  // Settings
  { name: "RiSettings3Line", category: "Settings" },
  { name: "RiDashboardLine", category: "Settings" },
  { name: "RiSwitchLine", category: "Settings" },
  
  // Actions
  { name: "RiAddLine", category: "Actions" },
  { name: "RiAddCircleLine", category: "Actions" },
  { name: "RiSubtractLine", category: "Actions" },
  { name: "RiCloseLine", category: "Actions" },
  { name: "RiEditLine", category: "Actions" },
  { name: "RiDeleteBinLine", category: "Actions" },
  { name: "RiSaveLine", category: "Actions" },
  { name: "RiRefreshLine", category: "Actions" },
  { name: "RiRepeatLine", category: "Actions" },
  { name: "RiReplyLine", category: "Actions" },
  { name: "RiUninstallLine", category: "Actions" },
  
  // Search & Filter
  { name: "RiSearchLine", category: "Search" },
  { name: "RiFilterLine", category: "Filter" },
  { name: "RiSortAsc", category: "Sort" },
  { name: "RiScanLine", category: "Search" },
  { name: "RiZoomInLine", category: "Search" },
  { name: "RiZoomOutLine", category: "Search" },
  
  // Download & Upload
  { name: "RiDownloadLine", category: "Download" },
  { name: "RiUploadLine", category: "Upload" },
  
  // Share & Link
  { name: "RiShareLine", category: "Share" },
  { name: "RiLinksLine", category: "Link" },
  { name: "RiExternalLinkLine", category: "External" },
  
  // Alerts
  { name: "RiErrorWarningLine", category: "Alerts" },
  { name: "RiInformationLine", category: "Alerts" },
  { name: "RiQuestionLine", category: "Alerts" },
  { name: "RiAlertLine", category: "Alerts" },
  
  // Ideas & Effects
  { name: "RiLightbulbLine", category: "Idea" },
  { name: "RiFlashlightLine", category: "Flash" },
  { name: "RiMagicLine", category: "Effects" },
  { name: "RiFocusLine", category: "Effects" },
  { name: "RiContrastLine", category: "Effects" },
  
  // Nature & Environment
  { name: "RiFireLine", category: "Nature" },
  { name: "RiRocketLine", category: "Nature" },
  { name: "RiLeafLine", category: "Nature" },
  { name: "RiRecycleLine", category: "Nature" },
  { name: "RiUmbrellaLine", category: "Nature" },
  
  // Weather
  { name: "RiCloudLine", category: "Weather" },
  { name: "RiRainyLine", category: "Weather" },
  { name: "RiSnowyLine", category: "Weather" },
  { name: "RiWindyLine", category: "Weather" },
  { name: "RiFoggyLine", category: "Weather" },
  { name: "RiHazeLine", category: "Weather" },
  { name: "RiDrizzleLine", category: "Weather" },
  { name: "RiShowersLine", category: "Weather" },
  { name: "RiMoonLine", category: "Weather" },
  { name: "RiSunLine", category: "Weather" },
  { name: "RiCelsiusLine", category: "Weather" },
  { name: "RiThermometerLine", category: "Weather" },
  { name: "RiTornadoLine", category: "Weather" },
  
  // Database & Server
  { name: "RiDatabaseLine", category: "Database" },
  { name: "RiServerLine", category: "Server" },
  { name: "RiHardDriveLine", category: "Database" },
  
  // Device
  { name: "RiDeviceLine", category: "Device" },
  { name: "RiTabletLine", category: "Device" },
  { name: "RiMouseLine", category: "Device" },
  { name: "RiKeyboardBoxLine", category: "Device" },
  { name: "RiPrinterLine", category: "Device" },
  { name: "RiBatteryChargeLine", category: "Device" },
  { name: "RiUsbLine", category: "Device" },
  { name: "RiBluetoothLine", category: "Device" },
  { name: "RiWifiLine", category: "Device" },
  { name: "RiCastLine", category: "Device" },
  { name: "RiRadioLine", category: "Device" },
  { name: "RiSignalTowerLine", category: "Device" },
  
  // Volume
  { name: "RiVolumeUpLine", category: "Volume" },
  { name: "RiVolumeDownLine", category: "Volume" },
  { name: "RiVolumeMuteLine", category: "Volume" },
  
  // Security
  { name: "RiShieldLine", category: "Security" },
  { name: "RiLockLine", category: "Security" },
  { name: "RiLockUnlockLine", category: "Security" },
  { name: "RiKeyLine", category: "Security" },
  { name: "RiSafeLine", category: "Security" },
  { name: "RiPoliceBadgeLine", category: "Security" },
  { name: "RiRegisteredLine", category: "Security" },
  
  // Shopping & Finance
  { name: "RiShoppingBagLine", category: "Shopping" },
  { name: "RiShoppingCartLine", category: "Shopping" },
  { name: "RiCouponLine", category: "Shopping" },
  { name: "RiDiscountPercentLine", category: "Shopping" },
  { name: "RiTicketLine", category: "Shopping" },
  { name: "RiWalletLine", category: "Finance" },
  { name: "RiMoneyDollarBoxLine", category: "Finance" },
  { name: "RiVisaLine", category: "Finance" },
  { name: "RiPaypalLine", category: "Finance" },
  
  // Events & Gifts
  { name: "RiGiftLine", category: "Events" },
  { name: "RiCupLine", category: "Events" },
  { name: "RiTrophyLine", category: "Events" },
  { name: "RiVipCrownLine", category: "Events" },
  
  // Other
  { name: "RiFlagLine", category: "Flags" },
  { name: "RiFoldersLine", category: "Folders" },
  { name: "RiGovernmentLine", category: "Government" },
  { name: "RiHotelLine", category: "Travel" },
  { name: "RiRestaurantLine", category: "Food" },
  { name: "RiTruckLine", category: "Delivery" },
  { name: "RiInfinityLine", category: "Symbols" },
  { name: "RiInputMethodLine", category: "Input" },
  { name: "RiCodeLine", category: "Development" },
  { name: "RiTerminalBoxLine", category: "Development" },
  { name: "RiGitBranchLine", category: "Development" },
  { name: "RiGitCommitLine", category: "Development" },
  { name: "RiGitMergeLine", category: "Development" },
  { name: "RiQrCodeLine", category: "Scanner" },
  { name: "RiToolsLine", category: "Tools" },
  { name: "RiScissorsLine", category: "Tools" },
  { name: "RiRobotLine", category: "AI" },
  { name: "RiGuideLine", category: "Navigation" },
  { name: "RiEyeLine", category: "Vision" },
  { name: "RiStarLine", category: "Rating" },
  { name: "RiCheckLine", category: "Check" },
  { name: "RiCheckboxCircleLine", category: "Check" },
  { name: "RiThumbUpLine", category: "Reactions" },
  { name: "RiThumbDownLine", category: "Reactions" },
  { name: "RiEmotionHappyLine", category: "Emotions" },
  { name: "RiEmotionSadLine", category: "Emotions" },
  { name: "RiRssLine", category: "Social" },
  { name: "RiTableAltLine", category: "Tables" },
  
  // Social Media
  { name: "RiGithubLine", category: "Social" },
  { name: "RiGoogleLine", category: "Social" },
  { name: "RiInstagramLine", category: "Social" },
  { name: "RiLinkedinBoxLine", category: "Social" },
  { name: "RiRedditLine", category: "Social" },
  { name: "RiSkypeLine", category: "Social" },
  { name: "RiSlackLine", category: "Social" },
  { name: "RiSnapchatLine", category: "Social" },
  { name: "RiSpotifyLine", category: "Social" },
  { name: "RiStackOverflowLine", category: "Social" },
  { name: "RiTelegramLine", category: "Social" },
  { name: "RiTiktokLine", category: "Social" },
  { name: "RiTwitchLine", category: "Social" },
  { name: "RiTwitterLine", category: "Social" },
  { name: "RiWhatsappLine", category: "Social" },
  { name: "RiWindowsLine", category: "Social" },
  { name: "RiYoutubeLine", category: "Social" },
  { name: "RiZcoolLine", category: "Social" },
  
  // Customer Service
  { name: "RiCustomerServiceLine", category: "Support" },
  
  // Home
  { name: "RiHomeLine", category: "Home" },
];

// تصدير جميع الفئات المتاحة للاستخدام
export const availableCategories = [
  "All",
  "Document",
  "Education",
  "Media",
  "World",
  "User",
  "Group",
  "Health",
  "Business",
  "Chat",
  "Communication",
  "Location",
  "Calendar",
  "Time",
  "Settings",
  "Actions",
  "Search",
  "Filter",
  "Sort",
  "Download",
  "Upload",
  "Share",
  "Link",
  "External",
  "Alerts",
  "Idea",
  "Flash",
  "Effects",
  "Nature",
  "Weather",
  "Database",
  "Server",
  "Device",
  "Volume",
  "Security",
  "Shopping",
  "Finance",
  "Events",
  "Flags",
  "Folders",
  "Government",
  "Medical",
  "Travel",
  "Food",
  "Delivery",
  "Symbols",
  "Input",
  "Development",
  "Scanner",
  "Tools",
  "AI",
  "Navigation",
  "Goals",
  "Vision",
  "Rating",
  "Check",
  "Reactions",
  "Emotions",
  "Social",
  "Support",
  "Home",
  "Tables",
];